### ISSUE TITLE
F3 or F4 - update messaging

### ISSUE THREAD

**Issue by kestlund** [projecthydra-labs/power-steering#1]
- Document from Hydra meeting in Nov. '14: https://docs.google.com/document/d/1VvaOD43TzRDCM4BbDb3HPg_q85U8EaGdT_XBw69JU2c/edit#heading=h.2y71bhbusxuc -> summary to go on Hydra.org
- DCE blog post: http://curationexperts.com/2015/01/05/adopting-hydra-in-2015/
- Factor in contingencies such as Avalon
- Agenda item for next Hydra partners call

**Comment by mark-dce** [comment]
Update FAQ page on wiki

**Comment by kestlund** [comment]
https://wiki.duraspace.org/display/hydra/Fedora+3+to+4+Migration+Interest+Group
