### ISSUE TITLE
Code of Conduct Script

### ISSUE THREAD

**Issue by kestlund** [projecthydra-labs/power-steering#17]

**Comment by mark-dce** [comment]
See straw dog at https://docs.google.com/presentation/d/1I_ZosKN4Y39kesAUAHv7sKv4KHBkW6344XN4Qaq_hR8/edit?usp=sharing

**Comment by azaroth42** [comment]
+1 Looks good to me. Much better than my flustered, off-the-cuff attempt! :)

On Sat, Mar 28, 2015 at 9:30 PM, Mark Bussey notifications@github.com
wrote:

> See straw dog at
> https://docs.google.com/presentation/d/1I_ZosKN4Y39kesAUAHv7sKv4KHBkW6344XN4Qaq_hR8/edit?usp=sharing
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/projecthydra-labs/power-steering/issues/17#issuecomment-87356711
> .

## 

Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305
