### ISSUE TITLE
Translate Architecture Diagram to Re-usable Format

### ISSUE THREAD

**Issue by kestlund** [projecthydra-labs/power-steering#2]
![2015-03-27 13 53 56](https://cloud.githubusercontent.com/assets/2481327/6877368/b5fc1d74-d48d-11e4-87f5-769224a93903.jpg)

**Comment by mark-dce** [comment]
Mark & Mike will be circulating drafts 3rd week of March & would love help!

**Comment by mjgiarlo** [comment]
`s/March/May/` ?

**Comment by kestlund** [comment]
Is this still accurate or should we just close?

**Comment by kestlund** [comment]
out-dated; closing

**Comment by mark-dce** [comment]
@kestlund @mjgiarlo - FYI @bess  and I have a commitment to addressing this as part of Introductory Hydra Camp content.  However, I'm lobbying to invert the requirement and make "develop a visual representation of the Hydra stack" a learner driven activity at camp.  Once we have some feedback from new adopters about what ideas and formats resonate with them, we'll draw up a cleaner version (if needed) for use on the wiki, etc.
