### ISSUE TITLE
Create a best practice document on hydra event facilitation

### ISSUE THREAD

**Issue by kestlund** [projecthydra-labs/power-steering#24]

**Comment by kestlund** [comment]
Include information on how to implement code of conduct.

**Comment by kestlund** [comment]
E.g. Regional meetings

**Comment by newmanld** [comment]
See https://wiki.duraspace.org/display/hydra/Organizing+Regional+Meetings+-+draft+guidance    @kcariani started this page.  @kcariani and I are collaborating.

**Comment by newmanld** [comment]
May need clarification as to scope - is this issue just about regional meetings or any Hydra Event?  (And is there a need for the distinction?)

**Comment by newmanld** [comment]
We determined that our scope was regional meetings.  See these two pages.  The word 'draft' has been removed from the second page:
https://wiki.duraspace.org/display/hydra/Hydra+Regional+Meetings
https://wiki.duraspace.org/display/hydra/Organizing+Regional+Meetings
