### ISSUE TITLE
Identify cross-institutional needs for architecture components

### ISSUE THREAD

**Issue by kestlund** [projecthydra-labs/power-steering#34]
Using diagram from March 2015 meeting

**Comment by tpendragon** [comment]
I honestly don't remember what this entailed. I believe it was to pull together what features we all wanted from one another? I think a lot of that happened in the move to Curation Concerns, though, and as it's been a year if this is still a need it should probably start with a call to Hydra Tech, which I'm happy to send out.

**Comment by mjgiarlo** [comment]
I don't remember either but I agree with your conclusion.

**Comment by kestlund** [comment]
I suggest closing this issue. Any concerns?
