### ISSUE TITLE
Proposal for venues

### ISSUE THREAD

**Issue by jeremyf** [projecthydra-labs/power-steering#37]
I would like to propose that a criteria for selecting locations include consideration for "Discriminatory Climate" of the host location (for example the state of Indiana's discriminatory climate is rather high). I'm not advocating for the climate to be a deal breaker, but to help acknowledge that we will take action to engage and ensure that all participants are both aware of the environment and that we have done due diligence in determining the allies.

**Comment by kestlund** [comment]
Make best efforts and follow best practices that DPLAfest and OR used in providing informative information for attendees.
