### ISSUE TITLE
Amend the Anti-Harassment Policy and process for handling conflicts / issues

### ISSUE THREAD

**Issue by kestlund** [projecthydra-labs/power-steering#52]

**Comment by mark-dce** [comment]
Mike G., Bess S., Karen E., Mark B. to ringlead conversation at OR2015

**Comment by kestlund** [comment]
Activity for HydraConnect2015

**Comment by kestlund** [comment]
See OR conflict policy.

**Comment by mark-dce** [comment]
@richardGreen - you're assigned to this.  Is it something you want to take on?  If not, I'd be happy to take it and try to get it closed out before the end of the year.

**Comment by richardGreen** [comment]
Mark

I have absolutely no idea why I am assigned to this – I’d be most grateful if you’d take it on!

Richard (home but v jet-lagged!)

**Comment by mark-dce** [comment]
@richardGreen I'm guessing your name got on here because of the mention of the Open Repositories policy and your association with both groups.  I'm re-assigning the ticket to myself.

**Comment by kestlund** [comment]
completed?

**Comment by kestlund** [comment]
https://wiki.duraspace.org/display/samvera/Anti-Harassment+Policy
