### ISSUE TITLE
Resolve Code of conduct, Anti-harassment, and Participant guide conflicts

### ISSUE THREAD

**Issue by mark-dce** [projecthydra-labs/power-steering#53]
**ACCEPTANCE CRITERIA**
- [ ] Make links on main project page clear
- [ ] Make sure Anti-harassment policy is clear
  https://wiki.duraspace.org/display/hydra/Anti-Harassment+Policy
- [ ] Remove or formalize Code-of-Conduct (redirect to Anti-Harassment) https://wiki.duraspace.org/display/hydra/Code+of+Conduct
- [ ] Link to Participant Guide where appropriate
  https://docs.google.com/presentation/d/1I_ZosKN4Y39kesAUAHv7sKv4KHBkW6344XN4Qaq_hR8/edit#slide=id.p4

**Comment by mark-dce** [comment]
Could possibly defer this to [Hydra Allies Interest Group](https://wiki.duraspace.org/display/hydra/Hydra+Allies+Interest+Group)

**Comment by kestlund** [comment]
Will the new DuraSpace code of conduct be something to subsume under rather than a Hydra specific one?

**Comment by kestlund** [comment]
Completed.
