### ISSUE TITLE
Hydra Camp with pair programming

### ISSUE THREAD

**Issue by kestlund** [projecthydra-labs/power-steering#8]
Note: also as a way to try to get at an intermediate Hydra Camp

**Comment by mark-dce** [comment]
Mark to send out survey and find interested candidates and dates.

**Comment by kestlund** [comment]
Karen sent out survey. Results: https://drive.google.com/folderview?id=0B9PlX06oLe-0NkJNOURGMnYxN2c&usp=drive_web

**Comment by kestlund** [comment]
Advanced Hydra Camp coming for 2017

**Comment by mark-dce** [comment]
@kestlund - no fair closing tickets @bess and I did the work for.  You're stealing all the endorphins!!!

**Comment by kestlund** [comment]
I always prune.  ;-)
