### ISSUE TITLE
Hire a Community Manager to help communication with IG/WG & Community

### ISSUE THREAD

**Issue by evvivaweinraub** [projecthydra-labs/power-steering#83]
A number of the recommendations regarding IG/WG's would benefit from having an owner, e.g., writing up periodic update digests, making sure IG/WG calls are on the calendar, and more. It would be good to explore using Hydra $ to fund a community manager for some of these, until/unless a volunteer within the community steps forward to take this on.

**Comment by richardGreen** [comment]
Duplicate of 65.

**Comment by kestlund** [comment]
Closing as Duplicate of #65. Adding cross-refs.
