### ISSUE TITLE
Web Communication Strategy

### ISSUE THREAD

**Issue by evvivaweinraub** [projecthydra-labs/power-steering#84]
Relationship to wiki documentation, clear pathways for new people to onboard (who aren't developers)

Especially with Hybox rolling out - likely to impact new audiences for Hydra.

Likely an activity for a community manager - see ticket 83.

**Comment by richardGreen** [comment]
This is covered by the on-going work around the web presence and effectively duplicates 14.

**Comment by kestlund** [comment]
Closing as duplicate. Adding reference to #14
