### ISSUE TITLE
Purchase an organizational Slack account

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/power-steering#86]
Currently Slack only stores 10k messages, if we purchased an account, we would be able to preserve a full message history.

**Comment by mark-dce** [comment]
We're investigating getting an open source pricing discount.  Currently we've got 305 users in the slack organization, Slack Standard is $6.67/mo per user = $24,414/year.  
https://project-hydra.slack.com/pricing/slack-for-teams 

I'm thinking we don't want to limit users, so we'd need a pretty hefty discount - or better a flat fee structure for Project Hydra.  I'll keep folks posted with what we find out.

**Comment by mark-dce** [comment]
@declanfleming - thanks for the pointer to https://get.slack.help/hc/en-us/articles/204368833
Slack for Nonprofits - discount pricing

**Comment by mark-dce** [comment]
So, it looks like at our current size, we'd be talking 305 users x $6.67 user-per-month x 12 months-per-year x 15% (85% discount) = $3661.83 per year including discount.

At 500 users on the Slack channel with the 86% discount off standard pricing, we'd be just over $6K per year.  Rachel is going to try to negotiate something better in the next week or so.

**Comment by mark-dce** [comment]
Pasting comment thread from Slack for context:

```
(project-hydra.slack.com).
#general 

Mark Matienzo 8:59 AM, Oct 12th
@tdonohue nope, unfortunately. only one per organization.

Mike Giarlo 9:19 AM, Oct 12th
@grosscol yeah, there are #powersteering folks in here. I believe @mhbussey is actively looking into this.

Colin Gross 9:19 AM, Oct 12th
Sweet. Sounds like it's in good hands.

Mike Giarlo 9:20 AM, Oct 12th
the idea of a DuraSpace Slack team that all DSpace, Hydra, Fedora, and VIVO projects can use (an idea @declan raised last night) is intriguing, but that'd probably wind up being prohibitively expensive for DuraSpace.
```

**Comment by mark-dce** [comment]
Slack responded to Rachel that they don't have capacity to make any special arrangements for Hydra outside of the non-profit pricing and encouraged us to apply for that.  I've written up a summary and backgrounder for the Hydra Steering Group and requested that they make a decision about next steps on the 10/28 Steering Group call.

**Comment by kestlund** [comment]
Using http://slackarchive.io/ and deferred pricing after 1 year pilot
